# meta-compulab 

## CompuLab NXP SoC based boards
This layer can be used separatelly.

* Provided MACHINE: cm-fx6-evk, cl-som-imx6ul, cl-som-imx7, iot-gate-imx7, sbc-iot-imx7, ucm-imx7

### Install the i.MX NXP BSP repo
[source,console]
$: repo init -u git://git.freescale.com/imx/fsl-arm-yocto-bsp.git -b imx-4.1-krogoth

### Download the Yocto Project NXP Layers:
[source,console]
$: repo sync

### Clone meta-compulab layer:
[source,console]
$: git clone https://github.com/compulab/yocto-compulab-layer.git source/meta-compulab

### Build Procedure
#### Select one of the supported machines: cm-fx6-evk, cl-som-imx6ul, cl-som-imx7
IMPORTANT: Change the below <mach name> to the actual supported machine name.

NOTE: For *iot-gate-imx7*, *sbc-iot-imx7* and *ucm-imx7*, use *cl-som-imx7* target for <mach name>.

[source,console]
$: export MACHINE=<mach name>

#### Select an available disptro: x11/fb/xwayland/wayland
[source,console]
$: export DISTRO=fsl-imx-x11
or
$: export DISTRO=fsl-imx-fb
or
$: export DISTRO=fsl-imx-xwayland
or
$: export DISTRO=fsl-imx-wayland

#### Create Build Environment:
* Issue `NXP` Setup Script
[source,console]
$: source fsl-setup-release.sh -b build-${MACHINE}-${DISTRO}

* Issue `CompuLab` Setup Script
[source,console]
$: source ../sources/meta-compulab/bb-tools/setup-compulab-env

#### Build
[source,console]
$: bitbake fsl-image-gui
or
$: bitbake fsl-image-qt5
