# meta-compulab 

## CompuLab NXP SoC based boards
This layer can be used separatelly.

* Provided MACHINE: cm-fx6-evk, cl-som-imx6ul, cl-som-imx7, iot-gate-imx7, sbc-iot-imx7

### Install the i.MX NXP BSP repo
[source,console]
$: repo init -u git://git.freescale.com/imx/fsl-arm-yocto-bsp.git -b imx-4.1-krogoth

### Download the Yocto Project NXP Layers:
[source,console]
$: repo sync

### Clone meta-compulab layer:
[source,console]
$: git clone https://github.com/compulab/yocto-compulab-layer.git source/meta-compulab

### Build Procedure
#### Select one of the supported machines: cm-fx6-evk, cl-som-imx6ul, cl-som-imx7
IMPORTANT: Change the below <mach name> to the actual supported machine name.

NOTE: For *iot-gate-imx7* and *sbc-iot-imx7*, use *cl-som-imx7* target for <mach name>.

[source,console]
$: export MACHINE=<mach name>

#### Select an available disptro: x11/fb/xwayland/wayland
[source,console]
$: export DISTRO=fsl-imx-x11
or
$: export DISTRO=fsl-imx-fb
or
$: export DISTRO=fsl-imx-xwayland
or
$: export DISTRO=fsl-imx-wayland

#### Run i.MX NXP Yocto Project Setup:
[source,console]
$: source fsl-setup-release.sh -b build-${MACHINE}-${DISTRO}

#### Pre-Build Steps
* Add the meta-compulab location to the conf/bblayers.conf

[source,console]
$: [[ -f conf/bblayers.conf ]] && (sed -i '$aBBLAYERS += " ${BSPDIR}/sources/meta-compulab "' conf/bblayers.conf) || echo "Warning: Invalid Build Directory"

WARNING: Stop Here if warning shows up

* Add the second packaging option to the conf/local.conf

[source,console]
$: [[ -f conf/local.conf ]] && sed -i '/PACKAGE_CLASSES/ a PACKAGE_CLASSES += " package_deb"' conf/local.conf || echo "Warning: Invalid Build Directory"

#### Build
[source,console]
$: bitbake fsl-image-gui
or
$: bitbake fsl-image-qt5
